### PR TITLE
Koken

### PR DESCRIPTION
**Pull request by Kokenishii**
I created a script called kokenTest

### CODE REVIEW

**Comment by Kokenishii** [comment]
Looks bad to me

**Comment by Kokenishii** [comment]
But please merge it

**Comment by ncarbonara** [comment]
You're just being negative! :)

**Comment by Kokenishii** [comment]
Can someone merge it?!?!?!?!?

**Comment by Kokenishii** [comment]
I am dying

**Comment by mmg551** [comment]
Look on the bright side, it could be a lot worse :D

**Comment by Kokenishii** [comment]
thank you nick! yes

**Comment by ncarbonara** [comment]
Imma merge, yo!

**Comment by IanOlet** [comment]
Wait, what?

**Comment by mmg551** [comment]
go for it

**Pull request merged**
